---
apiVersion: v1
kind: Namespace
metadata:
  name: blue
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  namespace: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blue
  template: 
    metadata:
      labels:
        app: blue
    spec:
      containers:
      - name: blue
        image: docker.io/giriraj789/blue:v1
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: blue-svc
  namespace: blue
spec:
  selector:
    app: blue
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8080
