apiVersion: k8s.nginx.org/v1
kind: VirtualServerRoute
metadata:
  name: restapi-vsr 
  namespace: restapi
spec:
  host: cafe.example.com
  upstreams:
  - name: user 
    service: user-svc
    port: 8081
  subroutes:
  - path: /api/v1/users 
    action:
      pass: user
